import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print("")
print(b)
print(a+b)
print(a-b)
print(a**2)
print(a<2)
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
#Hadamard çarpımı
print(a*b)
print(b.T)
c=a.dot(b.T)
print(c)
print(a.sum())
print(a.max())
print(a.min())
print(a.sum(axis=1))
print(a.sum(axis=0))
print(np.sqrt(a))
print(np.square(a))
rastgele_dizi=np.random.random((3,3))
print(rastgele_dizi)
